version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../apps/api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    container_name: redis-dev
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  postgres:
    name: nest-db
  redis:
    name: nest-redis